name: Deployment
on:
  push:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: calling custom actions
        uses: ./.github/actions/cache-deps
      - name: Lint code
        run: npm run lint
 