name: Deployment
on:
  push:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: calling custom actions
        uses: Vishva-45/Called-repo@v1
        with:
          ipname: 'yes passed'
      - name: Lint code
        run: npm run lint
 